[package]
name = "asciicam"
version = "0.1.0"
edition = "2021"
authors = ["Vilhelm Bergsøe <vilhelmbergsoe@gmail.com>"]

[dependencies]
image = "0.23.14"
chrono = "0.4.22"
crossterm = "0.23"
v4l = "0.13.0"
mozjpeg = "0.9.4"
fast_image_resize = "1.0.0"
